name: Deploy to Deno Deploy
on:
  push:
    branches:
      - main  # 当主分支推送时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:  # 必须配置权限
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 30v0d.deno.dev  # 替换为你的 Deno Deploy 项目名称
          entrypoint: index.html           # 静态网站入口文件路径
          root: .                          # 部署根目录（当前工作目录）
          # include: "*.html,*.css"        # 可选：指定包含文件模式
          # exclude: "node_modules/**"     # 可选：排除文件模式
