name: Deploy to Deno Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@1.13.1
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_API_TOKEN }}
        with:
          project: your-deno-project-name  # 替换为实际项目名称
          entrypoint: index.html
          root: .
