name: Deploy Deno Site
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Deno Site
        uses: appleboy/scp-action@v2.14.0  # 明确版本号
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DENO_SITE_SSH_KEY }}
        with:
          host: 30v0d.deno.dev
          port: 22
          username: b9348
          path: /your/deploy/path  # 替换为实际路径
          recursive: true
          args: "-o StrictHostKeyChecking=no"

      - name: 确保文件路径正确
        run: cp index.html ./public/index.html
        working-directory: ${{ github.workspace }}
